inputs: outputs/layout_detection/formulas
outputs: outputs/latex_formulas
tasks:
  formula_recognition:
    model: formula_recognition_unimernet
    model_config:
      cfg_path: pdf_extract_kit/configs/unimernet.yaml
      model_path: models/MFR/unimernet_tiny
      visualize: False
